stages:
  - build
  - test
  - deploy

.setup_docker_cli: &setup_docker_cli
  - apt-get update
  - apt-get -y install ca-certificates curl gnupg lsb-release
  - mkdir -p /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  - apt-get -y install docker-ce-cli docker-compose-plugin

job-build:
  stage: build
  script:
    - echo "Building..."

job-test:
  stage: test
  needs: [job-build]
  image: node:16
  script:
    - cd gateway
    - npm ci
    - echo "Testing..."
    - npm test

job-static-analysis:
  stage: test
  needs: [job-test]
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: 
    - sonar-scanner
  allow_failure: true
  only:
    - project

job-deploy:
  stage: deploy
  before_script:
    - *setup_docker_cli
  needs: [job-static-analysis]
  script:
    - echo "Deploying..."
    - docker compose up -d --build --wait
