version: '3.9'

services:

  gateway:
    build: gateway/.
    volumes:
      - state_log:/logs
    ports:
      - 8083:3000

volumes:
  state_log:
  docker:
    type: bind
    source: /var/run/docker.sock
    target: /var/run/docker.sock
    read_only: true

networks:
  default:
    name: common_network
