version: '3.9'

# Dependency Order
# mq
# httpserv
# obse
# imed
# orig

services:

  mq:
    image: <registry_name>.azurecr.io/mq:latest

  orig:
    image: <registry_name>.azurecr.io/orig:latest
    depends_on:
      imed:
        condition: service_healthy

  imed:
    image: <registry_name>.azurecr.io/imed:latest
    depends_on:
      obse:
        condition: service_healthy

  obse:
    image: <registry_name>.azurecr.io/obse:latest
    volumes:
      - message_log:/logs
    depends_on:
      httpserv:
        condition: service_healthy

  httpserv:
    image: <registry_name>.azurecr.io/httpserv:latest
    volumes:
      - message_log:/logs
    ports:
      - 8080:3000
    depends_on:
      mq:
        condition: service_healthy

volumes:
  message_log:
    external: true

networks:
  default:
    name: common_network
    external: true
